# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Qtproject/mainwindow.ui',
# licensing of 'Qtproject/mainwindow.ui' applies.
#
# Created: Tue May  7 17:56:23 2019
#      by: pyside2-uic  running on PySide2 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1076, 1075)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabCenter = QtWidgets.QTabWidget(self.centralWidget)
        self.tabCenter.setObjectName("tabCenter")
        self.tabIdentification = QtWidgets.QWidget()
        self.tabIdentification.setObjectName("tabIdentification")
        self.gridLayout = QtWidgets.QGridLayout(self.tabIdentification)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tabIdentification)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_4 = QtWidgets.QFrame(self.groupBox_3)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_idn_image = QtWidgets.QLabel(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_idn_image.sizePolicy().hasHeightForWidth())
        self.label_idn_image.setSizePolicy(sizePolicy)
        self.label_idn_image.setMinimumSize(QtCore.QSize(400, 200))
        self.label_idn_image.setAlignment(QtCore.Qt.AlignCenter)
        self.label_idn_image.setObjectName("label_idn_image")
        self.gridLayout_7.addWidget(self.label_idn_image, 0, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.frame_4)
        self.widgetidb_button_container = QtWidgets.QWidget(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetidb_button_container.sizePolicy().hasHeightForWidth())
        self.widgetidb_button_container.setSizePolicy(sizePolicy)
        self.widgetidb_button_container.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widgetidb_button_container.setObjectName("widgetidb_button_container")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.widgetidb_button_container)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.pb_IDNprevious = QtWidgets.QPushButton(self.widgetidb_button_container)
        self.pb_IDNprevious.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pb_IDNprevious.setObjectName("pb_IDNprevious")
        self.horizontalLayout_14.addWidget(self.pb_IDNprevious)
        self.pb_selectIDN = QtWidgets.QPushButton(self.widgetidb_button_container)
        self.pb_selectIDN.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pb_selectIDN.setObjectName("pb_selectIDN")
        self.horizontalLayout_14.addWidget(self.pb_selectIDN)
        self.pb_IDNnext = QtWidgets.QPushButton(self.widgetidb_button_container)
        self.pb_IDNnext.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pb_IDNnext.setObjectName("pb_IDNnext")
        self.horizontalLayout_14.addWidget(self.pb_IDNnext)
        self.verticalLayout_5.addWidget(self.widgetidb_button_container)
        self.gridLayout_6.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tabIdentification)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.te_partialIDN = QtWidgets.QTextEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.te_partialIDN.sizePolicy().hasHeightForWidth())
        self.te_partialIDN.setSizePolicy(sizePolicy)
        self.te_partialIDN.setMaximumSize(QtCore.QSize(16777215, 32))
        self.te_partialIDN.setObjectName("te_partialIDN")
        self.horizontalLayout_5.addWidget(self.te_partialIDN)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.lv_parts = QtWidgets.QListView(self.groupBox_4)
        self.lv_parts.setObjectName("lv_parts")
        self.verticalLayout_3.addWidget(self.lv_parts)
        self.frame_5 = QtWidgets.QFrame(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(406, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.pb_nextIDN = QtWidgets.QPushButton(self.frame_5)
        self.pb_nextIDN.setObjectName("pb_nextIDN")
        self.horizontalLayout_4.addWidget(self.pb_nextIDN)
        self.verticalLayout_3.addWidget(self.frame_5)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.gridLayout_5.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_4, 0, 1, 1, 1)
        self.tabCenter.addTab(self.tabIdentification, "")
        self.tabCapture = QtWidgets.QWidget()
        self.tabCapture.setObjectName("tabCapture")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.tabCapture)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.groupBox_13 = QtWidgets.QGroupBox(self.tabCapture)
        self.groupBox_13.setObjectName("groupBox_13")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.groupBox_13)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.groupBox_6.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_6.setMaximumSize(QtCore.QSize(200, 16777215))
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_9 = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_9.addWidget(self.label_9)
        self.te_settings_freq = QtWidgets.QPlainTextEdit(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.te_settings_freq.sizePolicy().hasHeightForWidth())
        self.te_settings_freq.setSizePolicy(sizePolicy)
        self.te_settings_freq.setMaximumSize(QtCore.QSize(16777215, 32))
        self.te_settings_freq.setObjectName("te_settings_freq")
        self.verticalLayout_9.addWidget(self.te_settings_freq)
        self.label_13 = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_9.addWidget(self.label_13)
        self.te_settings_span = QtWidgets.QPlainTextEdit(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.te_settings_span.sizePolicy().hasHeightForWidth())
        self.te_settings_span.setSizePolicy(sizePolicy)
        self.te_settings_span.setMaximumSize(QtCore.QSize(16777215, 32))
        self.te_settings_span.setObjectName("te_settings_span")
        self.verticalLayout_9.addWidget(self.te_settings_span)
        self.label_12 = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_9.addWidget(self.label_12)
        self.te_settings_sampling = QtWidgets.QPlainTextEdit(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.te_settings_sampling.sizePolicy().hasHeightForWidth())
        self.te_settings_sampling.setSizePolicy(sizePolicy)
        self.te_settings_sampling.setMaximumSize(QtCore.QSize(16777215, 32))
        self.te_settings_sampling.setObjectName("te_settings_sampling")
        self.verticalLayout_9.addWidget(self.te_settings_sampling)
        spacerItem1 = QtWidgets.QSpacerItem(20, 223, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem1)
        self.verticalLayout_14.addWidget(self.groupBox_6)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_5.setMaximumSize(QtCore.QSize(200, 16777215))
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_14 = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_7.addWidget(self.label_14)
        self.te_capture_freq = QtWidgets.QPlainTextEdit(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.te_capture_freq.sizePolicy().hasHeightForWidth())
        self.te_capture_freq.setSizePolicy(sizePolicy)
        self.te_capture_freq.setMaximumSize(QtCore.QSize(16777215, 32))
        self.te_capture_freq.setReadOnly(True)
        self.te_capture_freq.setObjectName("te_capture_freq")
        self.verticalLayout_7.addWidget(self.te_capture_freq)
        self.label_10 = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_7.addWidget(self.label_10)
        self.te_capture_span = QtWidgets.QPlainTextEdit(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.te_capture_span.sizePolicy().hasHeightForWidth())
        self.te_capture_span.setSizePolicy(sizePolicy)
        self.te_capture_span.setMaximumSize(QtCore.QSize(16777215, 32))
        self.te_capture_span.setReadOnly(True)
        self.te_capture_span.setObjectName("te_capture_span")
        self.verticalLayout_7.addWidget(self.te_capture_span)
        self.label_11 = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_7.addWidget(self.label_11)
        self.te_capture_sampling = QtWidgets.QPlainTextEdit(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.te_capture_sampling.sizePolicy().hasHeightForWidth())
        self.te_capture_sampling.setSizePolicy(sizePolicy)
        self.te_capture_sampling.setMaximumSize(QtCore.QSize(16777215, 32))
        self.te_capture_sampling.setReadOnly(True)
        self.te_capture_sampling.setObjectName("te_capture_sampling")
        self.verticalLayout_7.addWidget(self.te_capture_sampling)
        spacerItem2 = QtWidgets.QSpacerItem(20, 223, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem2)
        self.verticalLayout_14.addWidget(self.groupBox_5)
        self.horizontalLayout_6.addWidget(self.groupBox_13)
        self.groupBox_8 = QtWidgets.QGroupBox(self.tabCapture)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_8.sizePolicy().hasHeightForWidth())
        self.groupBox_8.setSizePolicy(sizePolicy)
        self.groupBox_8.setMinimumSize(QtCore.QSize(200, 0))
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.groupBox_10 = QtWidgets.QGroupBox(self.groupBox_8)
        self.groupBox_10.setObjectName("groupBox_10")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_15 = QtWidgets.QLabel(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_7.addWidget(self.label_15)
        self.sb_capture_length = QtWidgets.QSpinBox(self.groupBox_10)
        self.sb_capture_length.setObjectName("sb_capture_length")
        self.horizontalLayout_7.addWidget(self.sb_capture_length)
        self.verticalLayout_11.addLayout(self.horizontalLayout_7)
        self.cb_capture_hw = QtWidgets.QComboBox(self.groupBox_10)
        self.cb_capture_hw.setObjectName("cb_capture_hw")
        self.verticalLayout_11.addWidget(self.cb_capture_hw)
        spacerItem3 = QtWidgets.QSpacerItem(20, 63, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem3)
        self.verticalLayout_10.addWidget(self.groupBox_10)
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_8)
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_18 = QtWidgets.QLabel(self.groupBox_9)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_8.addWidget(self.label_18)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.sb_capture_trigger_delay = QtWidgets.QSpinBox(self.groupBox_9)
        self.sb_capture_trigger_delay.setObjectName("sb_capture_trigger_delay")
        self.horizontalLayout_8.addWidget(self.sb_capture_trigger_delay)
        self.verticalLayout_8.addLayout(self.horizontalLayout_8)
        self.label_19 = QtWidgets.QLabel(self.groupBox_9)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_8.addWidget(self.label_19)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pb_capture_ext_trigger = QtWidgets.QPushButton(self.groupBox_9)
        self.pb_capture_ext_trigger.setObjectName("pb_capture_ext_trigger")
        self.horizontalLayout_10.addWidget(self.pb_capture_ext_trigger)
        self.verticalLayout_8.addLayout(self.horizontalLayout_10)
        self.label_20 = QtWidgets.QLabel(self.groupBox_9)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_8.addWidget(self.label_20)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pb_capture_trigger = QtWidgets.QPushButton(self.groupBox_9)
        self.pb_capture_trigger.setObjectName("pb_capture_trigger")
        self.horizontalLayout_9.addWidget(self.pb_capture_trigger)
        self.verticalLayout_8.addLayout(self.horizontalLayout_9)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem4)
        self.verticalLayout_10.addWidget(self.groupBox_9)
        self.horizontalLayout_6.addWidget(self.groupBox_8)
        self.groupBox_7 = QtWidgets.QGroupBox(self.tabCapture)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_7.sizePolicy().hasHeightForWidth())
        self.groupBox_7.setSizePolicy(sizePolicy)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.capture_preview = QtWidgets.QWidget(self.groupBox_7)
        self.capture_preview.setObjectName("capture_preview")
        self.gridLayout_9.addWidget(self.capture_preview, 0, 0, 1, 1)
        self.horizontalLayout_6.addWidget(self.groupBox_7)
        self.tabCenter.addTab(self.tabCapture, "")
        self.tabStorage = QtWidgets.QWidget()
        self.tabStorage.setObjectName("tabStorage")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.tabStorage)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_16 = QtWidgets.QLabel(self.tabStorage)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_12.addWidget(self.label_16)
        self.tv_storage = QtWidgets.QTableView(self.tabStorage)
        self.tv_storage.setObjectName("tv_storage")
        self.verticalLayout_12.addWidget(self.tv_storage)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem5)
        self.pb_storage_update = QtWidgets.QPushButton(self.tabStorage)
        self.pb_storage_update.setObjectName("pb_storage_update")
        self.horizontalLayout_11.addWidget(self.pb_storage_update)
        self.pb_storage_load = QtWidgets.QPushButton(self.tabStorage)
        self.pb_storage_load.setObjectName("pb_storage_load")
        self.horizontalLayout_11.addWidget(self.pb_storage_load)
        self.verticalLayout_12.addLayout(self.horizontalLayout_11)
        self.gridLayout_12.addLayout(self.verticalLayout_12, 0, 1, 1, 1)
        self.groupBox_14 = QtWidgets.QGroupBox(self.tabStorage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_14.sizePolicy().hasHeightForWidth())
        self.groupBox_14.setSizePolicy(sizePolicy)
        self.groupBox_14.setMaximumSize(QtCore.QSize(300, 16777215))
        self.groupBox_14.setObjectName("groupBox_14")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.groupBox_14)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_21 = QtWidgets.QLabel(self.groupBox_14)
        self.label_21.setObjectName("label_21")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.label_26 = QtWidgets.QLabel(self.groupBox_14)
        self.label_26.setObjectName("label_26")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_26)
        self.label_24 = QtWidgets.QLabel(self.groupBox_14)
        self.label_24.setObjectName("label_24")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.le_upload_author = QtWidgets.QLineEdit(self.groupBox_14)
        self.le_upload_author.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_upload_author.setObjectName("le_upload_author")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.le_upload_author)
        self.label_25 = QtWidgets.QLabel(self.groupBox_14)
        self.label_25.setObjectName("label_25")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self.le_upload_licence = QtWidgets.QLineEdit(self.groupBox_14)
        self.le_upload_licence.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_upload_licence.setObjectName("le_upload_licence")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.le_upload_licence)
        self.label_23 = QtWidgets.QLabel(self.groupBox_14)
        self.label_23.setObjectName("label_23")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.cb_upload_datatype = QtWidgets.QComboBox(self.groupBox_14)
        self.cb_upload_datatype.setCurrentText("")
        self.cb_upload_datatype.setObjectName("cb_upload_datatype")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.cb_upload_datatype)
        self.label_22 = QtWidgets.QLabel(self.groupBox_14)
        self.label_22.setObjectName("label_22")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.le_upload_version = QtWidgets.QLineEdit(self.groupBox_14)
        self.le_upload_version.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_upload_version.setObjectName("le_upload_version")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.le_upload_version)
        self.pt_upload_name = QtWidgets.QPlainTextEdit(self.groupBox_14)
        self.pt_upload_name.setObjectName("pt_upload_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.pt_upload_name)
        self.upload_date = QtWidgets.QDateTimeEdit(self.groupBox_14)
        self.upload_date.setObjectName("upload_date")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.upload_date)
        self.label_27 = QtWidgets.QLabel(self.groupBox_14)
        self.label_27.setObjectName("label_27")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.le_upload_tags = QtWidgets.QLineEdit(self.groupBox_14)
        self.le_upload_tags.setObjectName("le_upload_tags")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.le_upload_tags)
        self.verticalLayout_17.addLayout(self.formLayout)
        spacerItem6 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_17.addItem(spacerItem6)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem7)
        self.pb_storage_savelocal = QtWidgets.QPushButton(self.groupBox_14)
        self.pb_storage_savelocal.setObjectName("pb_storage_savelocal")
        self.horizontalLayout_15.addWidget(self.pb_storage_savelocal)
        self.pb_storage_upload = QtWidgets.QPushButton(self.groupBox_14)
        self.pb_storage_upload.setObjectName("pb_storage_upload")
        self.horizontalLayout_15.addWidget(self.pb_storage_upload)
        self.verticalLayout_17.addLayout(self.horizontalLayout_15)
        self.gridLayout_12.addWidget(self.groupBox_14, 0, 0, 1, 1)
        self.tabCenter.addTab(self.tabStorage, "")
        self.tabAnalysis = QtWidgets.QWidget()
        self.tabAnalysis.setObjectName("tabAnalysis")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.tabAnalysis)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.groupBox_12 = QtWidgets.QGroupBox(self.tabAnalysis)
        self.groupBox_12.setObjectName("groupBox_12")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_12)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_17 = QtWidgets.QLabel(self.groupBox_12)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_13.addWidget(self.label_17)
        self.tb_analysis_classifiers = QtWidgets.QTableView(self.groupBox_12)
        self.tb_analysis_classifiers.setObjectName("tb_analysis_classifiers")
        self.verticalLayout_13.addWidget(self.tb_analysis_classifiers)
        self.verticalLayout_15.addLayout(self.verticalLayout_13)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem8)
        self.pb_analysis_load = QtWidgets.QPushButton(self.groupBox_12)
        self.pb_analysis_load.setObjectName("pb_analysis_load")
        self.horizontalLayout_13.addWidget(self.pb_analysis_load)
        self.pb_analysis_run = QtWidgets.QPushButton(self.groupBox_12)
        self.pb_analysis_run.setObjectName("pb_analysis_run")
        self.horizontalLayout_13.addWidget(self.pb_analysis_run)
        self.verticalLayout_15.addLayout(self.horizontalLayout_13)
        self.gridLayout_11.addLayout(self.verticalLayout_15, 0, 0, 1, 1)
        self.horizontalLayout_12.addWidget(self.groupBox_12)
        self.groupBox_11 = QtWidgets.QGroupBox(self.tabAnalysis)
        self.groupBox_11.setObjectName("groupBox_11")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_11)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.tb_analysis_results = QtWidgets.QTableView(self.groupBox_11)
        self.tb_analysis_results.setObjectName("tb_analysis_results")
        self.verticalLayout_16.addWidget(self.tb_analysis_results)
        self.te_analysis_results = QtWidgets.QTextEdit(self.groupBox_11)
        self.te_analysis_results.setObjectName("te_analysis_results")
        self.verticalLayout_16.addWidget(self.te_analysis_results)
        self.gridLayout_10.addLayout(self.verticalLayout_16, 0, 0, 1, 1)
        self.horizontalLayout_12.addWidget(self.groupBox_11)
        self.tabCenter.addTab(self.tabAnalysis, "")
        self.tabReport = QtWidgets.QWidget()
        self.tabReport.setObjectName("tabReport")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tabReport)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.tabReport)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cb_report_template = QtWidgets.QComboBox(self.groupBox)
        self.cb_report_template.setObjectName("cb_report_template")
        self.verticalLayout_2.addWidget(self.cb_report_template)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 5, 0, 1, 1)
        self.le_report_id = QtWidgets.QLineEdit(self.groupBox)
        self.le_report_id.setMaximumSize(QtCore.QSize(400, 16777215))
        self.le_report_id.setObjectName("le_report_id")
        self.gridLayout_2.addWidget(self.le_report_id, 3, 1, 1, 1)
        self.le_report_date = QtWidgets.QLineEdit(self.groupBox)
        self.le_report_date.setMaximumSize(QtCore.QSize(400, 16777215))
        self.le_report_date.setObjectName("le_report_date")
        self.gridLayout_2.addWidget(self.le_report_date, 1, 1, 1, 1)
        self.le_report_technician = QtWidgets.QLineEdit(self.groupBox)
        self.le_report_technician.setMaximumSize(QtCore.QSize(400, 16777215))
        self.le_report_technician.setObjectName("le_report_technician")
        self.gridLayout_2.addWidget(self.le_report_technician, 0, 1, 1, 1)
        self.le_report_location = QtWidgets.QLineEdit(self.groupBox)
        self.le_report_location.setMaximumSize(QtCore.QSize(400, 16777215))
        self.le_report_location.setObjectName("le_report_location")
        self.gridLayout_2.addWidget(self.le_report_location, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.le_report_signoff = QtWidgets.QLineEdit(self.groupBox)
        self.le_report_signoff.setMaximumSize(QtCore.QSize(400, 16777215))
        self.le_report_signoff.setObjectName("le_report_signoff")
        self.gridLayout_2.addWidget(self.le_report_signoff, 5, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.te_report_details = QtWidgets.QTextEdit(self.groupBox)
        self.te_report_details.setObjectName("te_report_details")
        self.gridLayout_2.addWidget(self.te_report_details, 4, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem9)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pb_report_add_photos = QtWidgets.QPushButton(self.groupBox)
        self.pb_report_add_photos.setObjectName("pb_report_add_photos")
        self.horizontalLayout_2.addWidget(self.pb_report_add_photos)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem10)
        self.pb_report_generate = QtWidgets.QPushButton(self.groupBox)
        self.pb_report_generate.setObjectName("pb_report_generate")
        self.horizontalLayout_2.addWidget(self.pb_report_generate)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.gridLayout_3.addWidget(self.groupBox, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.tabReport)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_3 = QtWidgets.QFrame(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(600, 0))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.web_report_preview = QWebEngineView(self.frame_3)
        self.web_report_preview.setUrl(QtCore.QUrl("https://1.1.1.1/"))
        self.web_report_preview.setObjectName("web_report_preview")
        self.gridLayout_8.addWidget(self.web_report_preview, 0, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.frame_3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem11)
        self.pb_save_report = QtWidgets.QPushButton(self.groupBox_2)
        self.pb_save_report.setObjectName("pb_save_report")
        self.horizontalLayout_3.addWidget(self.pb_save_report)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.gridLayout_4.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame_2)
        self.tabCenter.addTab(self.tabReport, "")
        self.verticalLayout.addWidget(self.tabCenter)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1076, 23))
        self.menuBar.setObjectName("menuBar")
        self.menu_File = QtWidgets.QMenu(self.menuBar)
        self.menu_File.setObjectName("menu_File")
        self.menu_Help = QtWidgets.QMenu(self.menuBar)
        self.menu_Help.setObjectName("menu_Help")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.action_Wizard = QtWidgets.QAction(MainWindow)
        self.action_Wizard.setObjectName("action_Wizard")
        self.action_Exit = QtWidgets.QAction(MainWindow)
        self.action_Exit.setObjectName("action_Exit")
        self.action_Storage = QtWidgets.QAction(MainWindow)
        self.action_Storage.setObjectName("action_Storage")
        self.action_User_Manual = QtWidgets.QAction(MainWindow)
        self.action_User_Manual.setObjectName("action_User_Manual")
        self.action_Login = QtWidgets.QAction(MainWindow)
        self.action_Login.setObjectName("action_Login")
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_Login)
        self.menu_File.addSeparator()
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_Exit)
        self.menu_Help.addAction(self.action_User_Manual)
        self.menuBar.addAction(self.menu_File.menuAction())
        self.menuBar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(MainWindow)
        self.tabCenter.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "RF Forensics Tool v0.1", None, -1))
        self.groupBox_3.setTitle(QtWidgets.QApplication.translate("MainWindow", "Board Identification", None, -1))
        self.label_idn_image.setText(QtWidgets.QApplication.translate("MainWindow", "Image", None, -1))
        self.pb_IDNprevious.setText(QtWidgets.QApplication.translate("MainWindow", "<", None, -1))
        self.pb_selectIDN.setText(QtWidgets.QApplication.translate("MainWindow", "&Select", None, -1))
        self.pb_IDNnext.setText(QtWidgets.QApplication.translate("MainWindow", ">", None, -1))
        self.groupBox_4.setTitle(QtWidgets.QApplication.translate("MainWindow", "IC Identification", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("MainWindow", "Parital / Full ID", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("MainWindow", "Results", None, -1))
        self.pb_nextIDN.setText(QtWidgets.QApplication.translate("MainWindow", "Select &Part", None, -1))
        self.tabCenter.setTabText(self.tabCenter.indexOf(self.tabIdentification), QtWidgets.QApplication.translate("MainWindow", "Identification", None, -1))
        self.groupBox_13.setTitle(QtWidgets.QApplication.translate("MainWindow", "RF Settings", None, -1))
        self.groupBox_6.setTitle(QtWidgets.QApplication.translate("MainWindow", "Settings", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("MainWindow", "Frequency  (MHz)", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("MainWindow", "Span (MHz)", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("MainWindow", "Sampling (kHz)", None, -1))
        self.groupBox_5.setTitle(QtWidgets.QApplication.translate("MainWindow", "Suggested Settings", None, -1))
        self.label_14.setText(QtWidgets.QApplication.translate("MainWindow", "Frequency  (MHz)", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("MainWindow", "Span (MHz)", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("MainWindow", "Sampling (kHz)", None, -1))
        self.groupBox_8.setTitle(QtWidgets.QApplication.translate("MainWindow", "Trigger", None, -1))
        self.groupBox_10.setTitle(QtWidgets.QApplication.translate("MainWindow", "Capture Settings", None, -1))
        self.label_15.setText(QtWidgets.QApplication.translate("MainWindow", "Window Size", None, -1))
        self.groupBox_9.setTitle(QtWidgets.QApplication.translate("MainWindow", "Triggering", None, -1))
        self.label_18.setText(QtWidgets.QApplication.translate("MainWindow", "Delayed Trigger", None, -1))
        self.label_19.setText(QtWidgets.QApplication.translate("MainWindow", "External Trigger", None, -1))
        self.pb_capture_ext_trigger.setText(QtWidgets.QApplication.translate("MainWindow", "&Configure", None, -1))
        self.label_20.setText(QtWidgets.QApplication.translate("MainWindow", "Trigger", None, -1))
        self.pb_capture_trigger.setText(QtWidgets.QApplication.translate("MainWindow", "&Trigger Now", None, -1))
        self.groupBox_7.setTitle(QtWidgets.QApplication.translate("MainWindow", "Preview", None, -1))
        self.tabCenter.setTabText(self.tabCenter.indexOf(self.tabCapture), QtWidgets.QApplication.translate("MainWindow", "Capture", None, -1))
        self.label_16.setText(QtWidgets.QApplication.translate("MainWindow", "Load Saved Data", None, -1))
        self.pb_storage_update.setText(QtWidgets.QApplication.translate("MainWindow", "U&pdate from Server", None, -1))
        self.pb_storage_load.setText(QtWidgets.QApplication.translate("MainWindow", "&Load Selected", None, -1))
        self.groupBox_14.setTitle(QtWidgets.QApplication.translate("MainWindow", "Upload Current Data", None, -1))
        self.label_21.setText(QtWidgets.QApplication.translate("MainWindow", "Description", None, -1))
        self.label_26.setText(QtWidgets.QApplication.translate("MainWindow", "Date", None, -1))
        self.label_24.setText(QtWidgets.QApplication.translate("MainWindow", "Author", None, -1))
        self.label_25.setText(QtWidgets.QApplication.translate("MainWindow", "Licence", None, -1))
        self.le_upload_licence.setText(QtWidgets.QApplication.translate("MainWindow", "MIT", None, -1))
        self.label_23.setText(QtWidgets.QApplication.translate("MainWindow", "Datatype", None, -1))
        self.label_22.setText(QtWidgets.QApplication.translate("MainWindow", "Version", None, -1))
        self.le_upload_version.setText(QtWidgets.QApplication.translate("MainWindow", "0.0.1", None, -1))
        self.label_27.setText(QtWidgets.QApplication.translate("MainWindow", "Tags", None, -1))
        self.pb_storage_savelocal.setText(QtWidgets.QApplication.translate("MainWindow", "&Save Locally", None, -1))
        self.pb_storage_upload.setText(QtWidgets.QApplication.translate("MainWindow", "&Upload to Server", None, -1))
        self.tabCenter.setTabText(self.tabCenter.indexOf(self.tabStorage), QtWidgets.QApplication.translate("MainWindow", "Storage", None, -1))
        self.groupBox_12.setTitle(QtWidgets.QApplication.translate("MainWindow", "Analysis", None, -1))
        self.label_17.setText(QtWidgets.QApplication.translate("MainWindow", "Available Classifers", None, -1))
        self.pb_analysis_load.setText(QtWidgets.QApplication.translate("MainWindow", "&Load Models", None, -1))
        self.pb_analysis_run.setText(QtWidgets.QApplication.translate("MainWindow", "&Run", None, -1))
        self.groupBox_11.setTitle(QtWidgets.QApplication.translate("MainWindow", "Results", None, -1))
        self.tabCenter.setTabText(self.tabCenter.indexOf(self.tabAnalysis), QtWidgets.QApplication.translate("MainWindow", "Analysis", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Report Generation", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "Sign Off", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "Details", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Location", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "Report ID", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Technician", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Date", None, -1))
        self.pb_report_add_photos.setText(QtWidgets.QApplication.translate("MainWindow", "&Attach Photos", None, -1))
        self.pb_report_generate.setText(QtWidgets.QApplication.translate("MainWindow", "&Generate", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("MainWindow", "Report Preview", None, -1))
        self.pb_save_report.setText(QtWidgets.QApplication.translate("MainWindow", "&Save", None, -1))
        self.tabCenter.setTabText(self.tabCenter.indexOf(self.tabReport), QtWidgets.QApplication.translate("MainWindow", "Report", None, -1))
        self.menu_File.setTitle(QtWidgets.QApplication.translate("MainWindow", "&File", None, -1))
        self.menu_Help.setTitle(QtWidgets.QApplication.translate("MainWindow", "&Help", None, -1))
        self.action_Wizard.setText(QtWidgets.QApplication.translate("MainWindow", "&Wizard", None, -1))
        self.action_Exit.setText(QtWidgets.QApplication.translate("MainWindow", "E&xit", None, -1))
        self.action_Storage.setText(QtWidgets.QApplication.translate("MainWindow", "Local &Storage", None, -1))
        self.action_User_Manual.setText(QtWidgets.QApplication.translate("MainWindow", "&User Manual", None, -1))
        self.action_Login.setText(QtWidgets.QApplication.translate("MainWindow", "&Login", None, -1))

from PySide2.QtWebEngineWidgets import QWebEngineView
