# Generated by Django 2.1.7 on 2019-04-22 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for Classifier for file storage')),
                ('public', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(help_text='Textual description of the capture')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifier', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClassifierTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a record tag (e.g. Education, Crime Scene, IoT)', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='classifier',
            name='tag',
            field=models.ManyToManyField(help_text='Select a tag for this record', to='classifiers.ClassifierTag'),
        ),
    ]
