# Generated by Django 2.1.7 on 2019-04-22 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifier',
            name='name',
            field=models.CharField(default='test', help_text='Short description of the Classifier', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classifier',
            name='description',
            field=models.TextField(help_text='Textual description of the Classifiers'),
        ),
    ]
