# Generated by Django 2.1.7 on 2019-04-22 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers', '0002_auto_20190422_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifier',
            name='ml',
            field=models.CharField(default='Keras', help_text='Machine Learning Toolkit used', max_length=200),
            preserve_default=False,
        ),
    ]
