# Generated by Django 2.1.7 on 2019-04-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers', '0003_classifier_ml'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifier',
            name='data_preprocess',
            field=models.CharField(default='', help_text='Optional Python code to pre-process inoput array', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classifier',
            name='score_lables',
            field=models.CharField(default='', help_text='Semi-colon separated list of classifier score labels', max_length=400),
            preserve_default=False,
        ),
    ]
