# Generated by Django 2.1.7 on 2019-04-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers', '0004_auto_20190428_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifier',
            name='data_preprocess',
            field=models.TextField(help_text='Optional Python code to pre-process inoput array'),
        ),
    ]
