# Generated by Django 2.1.7 on 2019-04-28 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers', '0005_auto_20190428_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classifier',
            old_name='score_lables',
            new_name='score_labels',
        ),
    ]
