# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/miscdev/Nextcloud/Masters/Embedded_Test_Platform/UCGUI/UCGUI/mainwindow.ui',
# licensing of '/home/miscdev/Nextcloud/Masters/Embedded_Test_Platform/UCGUI/UCGUI/mainwindow.ui' applies.
#
# Created: Sun Apr  7 16:35:37 2019
#      by: pyside2-uic  running on PySide2 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(464, 417)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_commands = QtWidgets.QLabel(self.centralWidget)
        self.label_commands.setObjectName("label_commands")
        self.verticalLayout_4.addWidget(self.label_commands)
        self.sa_command_buttons = QtWidgets.QScrollArea(self.centralWidget)
        self.sa_command_buttons.setWidgetResizable(True)
        self.sa_command_buttons.setObjectName("sa_command_buttons")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 214, 346))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.sa_command_buttons.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_4.addWidget(self.sa_command_buttons)
        self.verticalLayout_6.addLayout(self.verticalLayout_4)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gb_device = QtWidgets.QGroupBox(self.centralWidget)
        self.gb_device.setObjectName("gb_device")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.gb_device)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_3 = QtWidgets.QLabel(self.gb_device)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_3)
        self.rb_cog4050 = QtWidgets.QRadioButton(self.gb_device)
        self.rb_cog4050.setChecked(True)
        self.rb_cog4050.setObjectName("rb_cog4050")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.rb_cog4050)
        self.rb_leonardo = QtWidgets.QRadioButton(self.gb_device)
        self.rb_leonardo.setObjectName("rb_leonardo")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.rb_leonardo)
        self.le_comport = QtWidgets.QLineEdit(self.gb_device)
        self.le_comport.setObjectName("le_comport")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.le_comport)
        self.pb_connect = QtWidgets.QPushButton(self.gb_device)
        self.pb_connect.setObjectName("pb_connect")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.pb_connect)
        self.label_4 = QtWidgets.QLabel(self.gb_device)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(6, QtWidgets.QFormLayout.LabelRole, spacerItem)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.verticalLayout_5.addWidget(self.gb_device)
        self.gb_testcommands = QtWidgets.QGroupBox(self.centralWidget)
        self.gb_testcommands.setObjectName("gb_testcommands")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.gb_testcommands)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.gb_testcommands)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.sb_runs = QtWidgets.QSpinBox(self.gb_testcommands)
        self.sb_runs.setProperty("value", 1)
        self.sb_runs.setObjectName("sb_runs")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.sb_runs)
        self.cb_runs_forever = QtWidgets.QCheckBox(self.gb_testcommands)
        self.cb_runs_forever.setObjectName("cb_runs_forever")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cb_runs_forever)
        self.label_2 = QtWidgets.QLabel(self.gb_testcommands)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.label_2)
        self.sb_duration = QtWidgets.QSpinBox(self.gb_testcommands)
        self.sb_duration.setObjectName("sb_duration")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.sb_duration)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.verticalLayout_5.addWidget(self.gb_testcommands)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.label_commands.setText(QtWidgets.QApplication.translate("MainWindow", "Commands", None, -1))
        self.gb_device.setTitle(QtWidgets.QApplication.translate("MainWindow", "Device", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Test Device", None, -1))
        self.rb_cog4050.setText(QtWidgets.QApplication.translate("MainWindow", "COG4050", None, -1))
        self.rb_leonardo.setText(QtWidgets.QApplication.translate("MainWindow", "Leonardo", None, -1))
        self.le_comport.setText(QtWidgets.QApplication.translate("MainWindow", "/dev/ttyACM0", None, -1))
        self.pb_connect.setText(QtWidgets.QApplication.translate("MainWindow", "&Connect", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "Serial Port", None, -1))
        self.gb_testcommands.setTitle(QtWidgets.QApplication.translate("MainWindow", "Test Command", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Runs", None, -1))
        self.cb_runs_forever.setText(QtWidgets.QApplication.translate("MainWindow", "Loop Forever", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Duration (ms)", None, -1))

