#ifndef _HWPLATFORM_H_
#define _HWPLATFORM_H_

/* Configuration header is generated by meson.
 * User specifies their board on the meson configure command.
 */
#include "config.h"

#include <drivers/gpio/adi_gpio.h>
#include <drivers/spi/adi_spi.h>

#if COG4050 || COG3029

#define SENSOR_SPI_NUM 2
#define SENSOR_SPI_CSN ADI_SPI_CS3

/* INT_WAKE0 */
#define SENSOR_IRQ_PORT ADI_GPIO_PORT0
#define SENSOR_IRQ_PIN ADI_GPIO_PIN_15

/* GPIO29 */
#define EQUIP_GEN_TRIGGER_PORT ADI_GPIO_PORT1
#define EQUIP_GEN_TRIGGER_PIN ADI_GPIO_PIN_13

#define SENSOR_POWER_ENABLE_REQUIRED 0
#define SENSOR_POWER_PORT 0
#define SENSOR_POWER_PIN 0

#endif

#if EZ_KIT

#define SENSOR_SPI_NUM 2
#define SENSOR_SPI_CSN ADI_SPI_CS3

/* GPIO35 */
#define SENSOR_IRQ_PORT ADI_GPIO_PORT2
#define SENSOR_IRQ_PIN ADI_GPIO_PIN_3

/* GPIO32 */
/* GPIO 12 */
#define EQUIP_GEN_TRIGGER_PORT ADI_GPIO_PORT2
#define EQUIP_GEN_TRIGGER_PIN ADI_GPIO_PIN_0

#define SENSOR_POWER_ENABLE_REQUIRED 0
#define SENSOR_POWER_PORT 0
#define SENSOR_POWER_PIN 0

#endif

#endif // _HWPLATFORM_H_
